runtime: nodejs16
service: default

automatic_scaling:
  max_instances: 1

handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: \1
    upload: (.*\..+)$

  # Catch all handler to index.html
  # - url: /.*
  #   static_files: index.html
  #   upload: index.html

  # https://github.com/mikesparr/app-engine-react-demo
  - url: .*
    static_files: index.html
    upload: index.html

  # Catch all handler to index.html
  - url: /*.*
    static_files: index.html
    upload: index.html
