name: Deploy to GCP App engines

on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/checkout@v3'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: 'main'
          commit-message: 'CI: bumps version to {{version}} [skip ci]'

      - run: yarn install --frozen-lockfile

      - run: yarn build:client
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

      - name: Copy client/app.yaml to client/build/app.yaml
        run: cp client/app.yaml client/build/app.yaml

      - name: Authenticating with GCP
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GH_ACTIONS_GCP_SA_KEY }}'

      - name: Deploy client app to default service
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          working_directory: client/build
          deliverables: app.yaml
          promote: true
          version: ${{ github.sha }}

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'digiroom-a'
          heroku_email: 'amoodaa@gmail.com'

      # - name: Make .env.production.local
      #   uses: SpicyPizza/create-envfile@v1.3
      #   with:
      #     envkey_DB_URL: ${{ secrets.DB_URL }}
      #     envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      #     envkey_ORIGIN: ${{ secrets.APP_ORIGIN }}
      #     envkey_CREDENTIALS: true
      #     envkey_YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      #     directory: server
      #     file_name: .env.production.local
      #     fail_on_empty: false

      # - name: Deploy Server app to server service
      #   uses: "google-github-actions/deploy-appengine@v0"
      #   with:
      #     deliverables: "app.yaml"
      #     promote: true
      #     version: ${{ github.sha }}
